<script setup lang="ts">
import { computed, reactive, watch } from 'vue'
import type { DNSRecord, RecordPayload } from '@/views/DNSView.vue'
const props=defineProps<{show:boolean;record:DNSRecord|null;zoneName:string;saving:boolean}>()
const emit=defineEmits<{(e:'update:show',v:boolean):void;(e:'save',payload:RecordPayload):void}>()
const drawerWidth=Math.min(520,window.innerWidth)
const types=['A','AAAA','CNAME','TXT','MX','SRV','CAA'].map(value=>({label:value,value}))
const ttlOptions=[{label:'Auto',value:1},60,120,300,600,900,1800,3600,7200,18000,43200,86400].map(item=>typeof item==='number'?{label:item<3600?`${item/60} 分钟`:`${item/3600} 小时`,value:item}:item)
const tags=[{label:'issue',value:'issue'},{label:'issuewild',value:'issuewild'},{label:'iodef',value:'iodef'}]
const form=reactive<any>({type:'A',name:'',content:'',ttl:1,proxied:false,priority:10,data:{service:'',proto:'_tcp',name:'',priority:0,weight:0,port:443,target:'',flags:0,tag:'issue',value:''}})
const supportsProxy=computed(()=>['A','AAAA','CNAME'].includes(form.type))
watch(()=>props.show,show=>{if(!show)return;const r=props.record;if(r){form.type=r.type;form.name=r.name;form.content=r.content||'';form.ttl=r.ttl;form.proxied=r.proxied;form.priority=r.priority??10;form.data={service:'',proto:'_tcp',name:'',priority:0,weight:0,port:443,target:'',flags:0,tag:'issue',value:'',...(r.data||{})}}else{form.type='A';form.name='';form.content='';form.ttl=1;form.proxied=false;form.priority=10;form.data={service:'',proto:'_tcp',name:'',priority:0,weight:0,port:443,target:'',flags:0,tag:'issue',value:''}}},{immediate:true})
watch(()=>form.type,()=>{if(!supportsProxy.value)form.proxied=false})
const save=()=>{const payload:RecordPayload={type:form.type,name:form.name,content:form.content,ttl:form.ttl,proxied:form.proxied};if(form.type==='MX')payload.priority=Number(form.priority);if(form.type==='SRV')payload.data={service:form.data.service,proto:form.data.proto,name:form.data.name,priority:Number(form.data.priority),weight:Number(form.data.weight),port:Number(form.data.port),target:form.data.target};if(form.type==='CAA')payload.data={flags:Number(form.data.flags),tag:form.data.tag,value:form.data.value};emit('save',payload)}
</script>
<template><n-drawer :show="show" placement="right" :width="drawerWidth" @update:show="emit('update:show',$event)"><n-drawer-content :title="record?'编辑 DNS 记录':'添加 DNS 记录'" closable><n-form label-placement="top"><n-form-item label="类型"><n-select v-model:value="form.type" :options="types" :disabled="!!record"/></n-form-item><n-form-item label="名称"><n-input v-model:value="form.name" :placeholder="`例如 api 或 ${zoneName}`"/></n-form-item>
<template v-if="['A','AAAA','CNAME','TXT'].includes(form.type)"><n-form-item :label="form.type==='TXT'?'内容':'目标'"><n-input v-model:value="form.content" :type="form.type==='TXT'?'textarea':'text'" :placeholder="form.type==='A'?'1.2.3.4':form.type==='AAAA'?'2001:db8::1':form.type==='CNAME'?'target.example.com':'文本内容'"/></n-form-item></template>
<template v-if="form.type==='MX'"><n-form-item label="邮件服务器"><n-input v-model:value="form.content" placeholder="mail.example.com"/></n-form-item><n-form-item label="优先级"><n-input-number v-model:value="form.priority" :min="0" :max="65535" class="w-full"/></n-form-item></template>
<template v-if="form.type==='SRV'"><div class="grid grid-cols-2 gap-x-3"><n-form-item label="服务"><n-input v-model:value="form.data.service" placeholder="_sip"/></n-form-item><n-form-item label="协议"><n-input v-model:value="form.data.proto" placeholder="_tcp"/></n-form-item></div><n-form-item label="名称"><n-input v-model:value="form.data.name" placeholder="example.com"/></n-form-item><div class="grid grid-cols-3 gap-x-3"><n-form-item label="优先级"><n-input-number v-model:value="form.data.priority" :min="0"/></n-form-item><n-form-item label="权重"><n-input-number v-model:value="form.data.weight" :min="0"/></n-form-item><n-form-item label="端口"><n-input-number v-model:value="form.data.port" :min="1" :max="65535"/></n-form-item></div><n-form-item label="目标"><n-input v-model:value="form.data.target" placeholder="service.example.com"/></n-form-item></template>
<template v-if="form.type==='CAA'"><div class="grid grid-cols-2 gap-x-3"><n-form-item label="Flag"><n-input-number v-model:value="form.data.flags" :min="0" :max="255" class="w-full"/></n-form-item><n-form-item label="Tag"><n-select v-model:value="form.data.tag" :options="tags"/></n-form-item></div><n-form-item label="Value"><n-input v-model:value="form.data.value" placeholder="letsencrypt.org"/></n-form-item></template>
<n-form-item label="TTL"><n-select v-model:value="form.ttl" :options="ttlOptions"/></n-form-item><n-form-item v-if="supportsProxy" label="Cloudflare Proxy"><div class="flex w-full items-center justify-between rounded border border-gray-200 px-3 py-2 dark:border-gray-700"><span class="text-sm">代理流量并隐藏源站地址</span><n-switch v-model:value="form.proxied"><template #checked>ON</template><template #unchecked>OFF</template></n-switch></div></n-form-item></n-form><template #footer><n-space><n-button @click="emit('update:show',false)">取消</n-button><n-button type="primary" :loading="saving" @click="save">{{record?'保存修改':'创建记录'}}</n-button></n-space></template></n-drawer-content></n-drawer></template>
