<script lang="ts">export interface DNSRecord{id:string;type:string;name:string;content:string;ttl:number;proxied:boolean;proxiable:boolean;priority?:number;data?:Record<string,any>;modified_on:string} export interface RecordPayload{type:string;name:string;content?:string;ttl:number;proxied:boolean;priority?:number;data?:Record<string,any>}</script>
<script setup lang="ts">
import { computed, h, onMounted, ref, watch } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { NButton, NPopconfirm, NSwitch, NTag, type DataTableColumns, type DataTableRowKey, useMessage } from 'naive-ui'
import { CloudOff, Edit3, Plus, RefreshCw, Search, Trash2 } from '@lucide/vue'
import { api } from '@/api'
import { useAppStore } from '@/stores/app'
import RecordDrawer from '@/components/RecordDrawer.vue'
const app=useAppStore(),route=useRoute(),router=useRouter(),message=useMessage(),loading=ref(false),saving=ref(false),records=ref<DNSRecord[]>([]),search=ref(''),typeFilter=ref<string|null>(null),proxyFilter=ref<string|null>(null),checked=ref<DataTableRowKey[]>([]),drawer=ref(false),editing=ref<DNSRecord|null>(null)
const zoneID=computed(()=>Number(route.query.zone||app.defaultZone?.id||0)),zone=computed(()=>app.zones.find(z=>z.id===zoneID.value)),typeOptions=['A','AAAA','CNAME','TXT','MX','SRV','CAA'].map(value=>({label:value,value})),proxyOptions=[{label:'已代理',value:'on'},{label:'仅 DNS',value:'off'}]
const displayContent=(r:DNSRecord)=>r.type==='SRV'&&r.data?`${r.data.priority} ${r.data.weight} ${r.data.port} ${r.data.target}`:r.type==='CAA'&&r.data?`${r.data.flags} ${r.data.tag} ${r.data.value}`:r.content
const filtered=computed(()=>{const q=search.value.trim().toLowerCase();return records.value.filter(r=>(!q||`${r.type} ${r.name} ${displayContent(r)}`.toLowerCase().includes(q))&&(!typeFilter.value||r.type===typeFilter.value)&&(!proxyFilter.value||(proxyFilter.value==='on'?r.proxied:!r.proxied)))})
const editable=(r:DNSRecord)=>['A','AAAA','CNAME','TXT','MX','SRV','CAA'].includes(r.type)
const ttl=(value:number)=>value===1?'Auto':value<3600?`${value/60} 分钟`:`${value/3600} 小时`
const load=async()=>{if(!zoneID.value){records.value=[];return}loading.value=true;checked.value=[];try{const response=await api.response<DNSRecord[]>(`/zones/${zoneID.value}/records`);records.value=response.data}catch(e:any){message.error(e.message)}finally{loading.value=false}}
const openAdd=()=>{editing.value=null;drawer.value=true};const openEdit=(r:DNSRecord)=>{editing.value=r;drawer.value=true}
const save=async(payload:RecordPayload)=>{saving.value=true;try{if(editing.value)await api.request(`/zones/${zoneID.value}/records/${editing.value.id}`,{method:'PUT',body:JSON.stringify(payload)});else await api.request(`/zones/${zoneID.value}/records`,{method:'POST',body:JSON.stringify(payload)});drawer.value=false;message.success(editing.value?'记录已更新':'记录已创建');await load()}catch(e:any){message.error(e.message)}finally{saving.value=false}}
const remove=async(r:DNSRecord)=>{try{await api.request(`/zones/${zoneID.value}/records/${r.id}`,{method:'DELETE'});message.success('记录已删除');await load()}catch(e:any){message.error(e.message)}}
const toggleProxy=async(r:DNSRecord,value:boolean)=>{const payload:RecordPayload={type:r.type,name:r.name,content:r.content,ttl:value?1:r.ttl,proxied:value,priority:r.priority,data:r.data};try{await api.request(`/zones/${zoneID.value}/records/${r.id}`,{method:'PUT',body:JSON.stringify(payload)});r.proxied=value;if(value)r.ttl=1;message.success(value?'已开启 Cloudflare Proxy':'已关闭 Cloudflare Proxy')}catch(e:any){message.error(e.message)}}
const batch=async(action:string)=>{if(!checked.value.length)return;try{const result=await api.request<{results:{success:boolean;error?:string}[]}>(`/zones/${zoneID.value}/records/batch`,{method:'POST',body:JSON.stringify({action,record_ids:checked.value})});const failed=result.results.filter(r=>!r.success).length;failed?message.warning(`${result.results.length-failed} 条成功，${failed} 条失败`):message.success('批量操作完成');await load()}catch(e:any){message.error(e.message)}}
const columns:DataTableColumns<DNSRecord>=[{type:'selection',disabled:r=>false},{title:'类型',key:'type',width:82,render:r=>h(NTag,{size:'small',bordered:true},{default:()=>r.type})},{title:'名称',key:'name',minWidth:210,render:r=>h('span',{class:'font-medium'},r.name)},{title:'内容',key:'content',minWidth:260,ellipsis:{tooltip:true},render:r=>h('span',{class:'record-value'},displayContent(r))},{title:'TTL',key:'ttl',width:100,render:r=>ttl(r.ttl)},{title:'Proxy',key:'proxied',width:100,render:r=>r.proxiable?h(NSwitch,{value:r.proxied,size:'small','onUpdate:value':(v:boolean)=>toggleProxy(r,v)},{checked:()=> 'ON',unchecked:()=> 'OFF'}):h('span',{class:'text-xs text-gray-400'},'-')},{title:'操作',key:'actions',width:94,render:r=>h('div',{class:'flex'},[h(NButton,{quaternary:true,circle:true,disabled:!editable(r),onClick:()=>openEdit(r)},{icon:()=>h(Edit3,{size:16})}),h(NPopconfirm,{onPositiveClick:()=>remove(r)},{trigger:()=>h(NButton,{quaternary:true,circle:true,type:'error'},{icon:()=>h(Trash2,{size:16})}),default:()=>`删除 ${r.name}？`})])}]
watch(zoneID,load);onMounted(async()=>{if(!app.zonesLoaded)await app.loadZones();if(!zoneID.value&&app.defaultZone)await router.replace({path:'/dns',query:{zone:app.defaultZone.id}});else await load()})
</script>
<template><div><div class="mb-5 flex flex-wrap items-start justify-between gap-3"><div><h1 class="page-title">DNS 记录</h1><p class="page-subtitle">{{zone?.name||'选择一个域名开始管理'}}</p></div><div class="flex gap-2"><n-button :loading="loading" :disabled="!zoneID" @click="load"><template #icon><RefreshCw :size="17"/></template>刷新</n-button><n-button type="primary" :disabled="!zoneID" @click="openAdd"><template #icon><Plus :size="17"/></template>添加记录</n-button></div></div>
<template v-if="zoneID"><div class="mb-3 flex flex-wrap gap-2"><n-input v-model:value="search" clearable placeholder="搜索名称或内容" style="min-width:220px;max-width:360px;flex:1 1 260px"><template #prefix><Search :size="16"/></template></n-input><n-select v-model:value="typeFilter" clearable placeholder="全部类型" :options="typeOptions" style="width:132px;flex:none"/><n-select v-model:value="proxyFilter" clearable placeholder="全部代理" :options="proxyOptions" style="width:132px;flex:none"/></div>
<div v-if="checked.length" class="mb-3 flex flex-wrap items-center gap-2 border-l-2 border-[#f6821f] bg-orange-50 px-3 py-2 text-sm dark:bg-orange-950/30"><b>已选 {{checked.length}} 条</b><n-popconfirm @positive-click="batch('delete')"><template #trigger><n-button size="small" type="error" secondary>批量删除</n-button></template>确认删除所选记录？</n-popconfirm><n-button size="small" @click="batch('proxy_on')">开启 Proxy</n-button><n-button size="small" @click="batch('proxy_off')">关闭 Proxy</n-button></div>
<div class="surface hidden overflow-hidden md:block"><n-data-table v-model:checked-row-keys="checked" :columns="columns" :data="filtered" :loading="loading" :row-key="(r:DNSRecord)=>r.id" :bordered="false" :pagination="{pageSize:25,showSizePicker:true,pageSizes:[25,50,100]}"/></div>
<div class="surface divide-y divide-gray-200 overflow-hidden md:hidden dark:divide-gray-700"><div v-for="r in filtered" :key="r.id" class="p-3"><div class="flex items-start gap-2"><n-checkbox :checked="checked.includes(r.id)" @update:checked="(v:boolean)=>checked=v?[...checked,r.id]:checked.filter(id=>id!==r.id)"/><n-tag size="small">{{r.type}}</n-tag><div class="min-w-0 flex-1"><div class="truncate text-sm font-semibold">{{r.name}}</div><div class="record-value mt-1 text-gray-500">{{displayContent(r)}}</div></div><n-button quaternary circle size="small" :disabled="!editable(r)" aria-label="编辑记录" @click="openEdit(r)"><Edit3 :size="16"/></n-button><n-popconfirm @positive-click="remove(r)"><template #trigger><n-button quaternary circle size="small" type="error" aria-label="删除记录"><Trash2 :size="16"/></n-button></template>删除 {{r.name}}？</n-popconfirm></div><div class="mt-3 flex items-center justify-between pl-7 text-xs text-gray-500"><span>TTL {{ttl(r.ttl)}}</span><n-switch v-if="r.proxiable" :value="r.proxied" size="small" @update:value="(v:boolean)=>toggleProxy(r,v)"/></div></div><n-empty v-if="!loading&&!filtered.length" class="py-14" description="没有匹配的 DNS 记录"/></div></template>
<div v-else class="surface py-20"><n-empty description="尚无可管理的域名"><template #icon><CloudOff :size="42"/></template><template #extra><n-button type="primary" @click="router.push('/tokens')">添加 API Token</n-button></template></n-empty></div>
<RecordDrawer v-model:show="drawer" :record="editing" :zone-name="zone?.name||''" :saving="saving" @save="save"/></div></template>
