<script setup lang="ts">
import { h, onMounted, ref } from 'vue'
import { NButton, NTag, type DataTableColumns, useMessage } from 'naive-ui'
import { Eye } from '@lucide/vue'
import { api } from '@/api'
interface Log {id:number;username:string;action:string;resource_type:string;resource_id:string;resource_name:string;before?:any;after?:any;success:boolean;error_message:string;ip_address:string;created_at:string}
const items=ref<Log[]>([]),loading=ref(false),page=ref(1),total=ref(0),detail=ref<Log|null>(null),message=useMessage()
const drawerWidth=Math.min(560,window.innerWidth)
const load=async()=>{loading.value=true;try{const r=await api.response<Log[]>(`/logs?page=${page.value}&per_page=50`);items.value=r.data;total.value=r.meta?.total||0}catch(e:any){message.error(e.message)}finally{loading.value=false}}
const columns:DataTableColumns<Log>=[{title:'时间',key:'created_at',width:180,render:r=>new Date(r.created_at).toLocaleString()},{title:'用户',key:'username',width:100},{title:'操作',key:'action',width:180,render:r=>h('span',{class:'font-medium'},r.action)},{title:'目标',key:'resource_name',ellipsis:{tooltip:true},render:r=>r.resource_name||r.resource_id||'-'},{title:'结果',key:'success',width:90,render:r=>h(NTag,{size:'small',type:r.success?'success':'error',bordered:false},{default:()=>r.success?'成功':'失败'})},{title:'详情',key:'detail',width:68,render:r=>h(NButton,{quaternary:true,circle:true,onClick:()=>detail.value=r},{icon:()=>h(Eye,{size:16})})}]
const pretty=(value:any)=>value==null?'无':JSON.stringify(value,null,2)
onMounted(load)
</script>
<template><div><div class="mb-5"><h1 class="page-title">操作日志</h1><p class="page-subtitle">DNS、凭据和安全设置的不可变更审计记录</p></div><div class="surface overflow-hidden"><n-data-table v-if="loading||items.length" :columns="columns" :data="items" :loading="loading" :bordered="false" :row-key="(r:Log)=>r.id"/><div v-if="total>50" class="flex justify-end border-t p-3 dark:border-gray-700"><n-pagination v-model:page="page" :item-count="total" :page-size="50" @update:page="load"/></div><n-empty v-if="!loading&&!items.length" class="py-16" description="暂无操作日志"/></div><n-drawer :show="!!detail" placement="right" :width="drawerWidth" @update:show="(v:boolean)=>!v&&(detail=null)"><n-drawer-content v-if="detail" title="操作详情" closable><dl class="grid grid-cols-[88px_1fr] gap-y-3 text-sm"><dt class="text-gray-500">时间</dt><dd>{{new Date(detail.created_at).toLocaleString()}}</dd><dt class="text-gray-500">用户</dt><dd>{{detail.username}}</dd><dt class="text-gray-500">操作</dt><dd>{{detail.action}}</dd><dt class="text-gray-500">目标</dt><dd class="break-all">{{detail.resource_name||detail.resource_id||'-'}}</dd><dt class="text-gray-500">来源 IP</dt><dd>{{detail.ip_address||'-'}}</dd></dl><n-divider/> <div class="mb-2 text-sm font-semibold">修改前</div><pre class="max-h-64 overflow-auto rounded bg-gray-100 p-3 text-xs dark:bg-black/30">{{pretty(detail.before)}}</pre><div class="mb-2 mt-5 text-sm font-semibold">修改后</div><pre class="max-h-64 overflow-auto rounded bg-gray-100 p-3 text-xs dark:bg-black/30">{{pretty(detail.after)}}</pre><n-alert v-if="!detail.success" class="mt-5" type="error">{{detail.error_message}}</n-alert></n-drawer-content></n-drawer></div></template>
