<script setup lang="ts">
import { h, onMounted, ref } from 'vue'
import { NButton, NPopconfirm, type DataTableColumns, useMessage } from 'naive-ui'
import { Edit3, KeyRound, Plus, ShieldCheck, Trash2 } from '@lucide/vue'
import { ApiError, api } from '@/api'
import { loginWithPasskey, registerPasskey } from '@/webauthn'
interface Passkey{id:number;name:string;created_at:string;last_used_at?:string}
const message=useMessage(),passkeys=ref<Passkey[]>([]),loading=ref(false),currentPassword=ref(''),newPassword=ref(''),confirmPassword=ref(''),changing=ref(false),reauthOpen=ref(false),reauthPassword=ref(''),reauthLoading=ref(false),pending=ref<null|(()=>Promise<void>)>(null),nameOpen=ref(false),passkeyName=ref(''),renameTarget=ref<Passkey|null>(null)
const load=async()=>{loading.value=true;try{passkeys.value=await api.request('/passkeys')}catch(e:any){message.error(e.message)}finally{loading.value=false}}
const changePassword=async()=>{if(newPassword.value!==confirmPassword.value){message.error('两次输入的新密码不一致');return}changing.value=true;try{await api.request('/auth/password',{method:'PUT',body:JSON.stringify({current_password:currentPassword.value,new_password:newPassword.value})});currentPassword.value=newPassword.value=confirmPassword.value='';message.success('密码已修改，其他会话已退出')}catch(e:any){message.error(e.message)}finally{changing.value=false}}
const requireReauth=(action:()=>Promise<void>)=>{pending.value=action;reauthPassword.value='';reauthOpen.value=true}
const afterReauth=async()=>{reauthOpen.value=false;const action=pending.value;pending.value=null;if(action)await action()}
const reauthPasswordSubmit=async()=>{reauthLoading.value=true;try{await api.request('/auth/reauth',{method:'POST',body:JSON.stringify({password:reauthPassword.value})});await afterReauth()}catch(e:any){message.error(e.message)}finally{reauthLoading.value=false}}
const reauthPasskey=async()=>{reauthLoading.value=true;try{await loginWithPasskey(true);await afterReauth()}catch(e:any){if(e?.name!=='NotAllowedError')message.error(e.message)}finally{reauthLoading.value=false}}
const openAdd=()=>{renameTarget.value=null;passkeyName.value='';nameOpen.value=true}
const saveName=async()=>{const name=passkeyName.value.trim();if(!name){message.error('请输入设备名称');return}nameOpen.value=false;if(renameTarget.value){try{await api.request(`/passkeys/${renameTarget.value.id}`,{method:'PATCH',body:JSON.stringify({name})});await load();message.success('名称已更新')}catch(e:any){message.error(e.message)}}else requireReauth(async()=>{try{await registerPasskey(name);await load();message.success('Passkey 已注册')}catch(e:any){if(e instanceof ApiError&&e.code==='reauthentication_required')return requireReauth(()=>registerPasskey(name).then(load));if(e?.name!=='NotAllowedError')message.error(e.message)}})}
const remove=(row:Passkey)=>requireReauth(async()=>{try{await api.request(`/passkeys/${row.id}`,{method:'DELETE'});await load();message.success('Passkey 已删除')}catch(e:any){message.error(e.message)}})
const rename=(row:Passkey)=>{renameTarget.value=row;passkeyName.value=row.name;nameOpen.value=true}
const columns:DataTableColumns<Passkey>=[{title:'设备名称',key:'name',render:r=>h('div',{class:'flex items-center gap-2 font-medium'},[h(KeyRound,{size:16,class:'text-orange-500'}),r.name])},{title:'创建时间',key:'created_at',width:180,render:r=>new Date(r.created_at).toLocaleString()},{title:'最后使用',key:'last_used_at',width:180,render:r=>r.last_used_at?new Date(r.last_used_at).toLocaleString():'尚未使用'},{title:'操作',key:'actions',width:92,render:r=>h('div',{class:'flex'},[h(NButton,{quaternary:true,circle:true,onClick:()=>rename(r)},{icon:()=>h(Edit3,{size:16})}),h(NPopconfirm,{onPositiveClick:()=>remove(r)},{trigger:()=>h(NButton,{quaternary:true,circle:true,type:'error'},{icon:()=>h(Trash2,{size:16})}),default:()=>`删除 ${r.name}？`})])}]
onMounted(load)
</script>
<template><div class="max-w-5xl"><div class="mb-5"><h1 class="page-title">设置</h1><p class="page-subtitle">管理管理员密码、Passkey 和认证设备</p></div><section class="surface mb-5"><div class="flex items-center justify-between border-b px-4 py-3 dark:border-gray-700"><div><h2 class="font-semibold">Passkey</h2><p class="mt-1 text-xs text-gray-500">使用设备生物识别或安全密钥登录</p></div><n-button type="primary" size="small" @click="openAdd"><template #icon><Plus :size="16"/></template>注册 Passkey</n-button></div><n-data-table v-if="loading||passkeys.length" :columns="columns" :data="passkeys" :loading="loading" :bordered="false" :row-key="(r:Passkey)=>r.id"/><n-empty v-else class="py-10" description="尚未注册 Passkey"/></section>
<section class="surface"><div class="border-b px-4 py-3 dark:border-gray-700"><h2 class="font-semibold">修改密码</h2><p class="mt-1 text-xs text-gray-500">修改后会撤销其他已登录会话</p></div><div class="max-w-lg p-4"><n-form><n-form-item label="当前密码"><n-input v-model:value="currentPassword" type="password" show-password-on="click"/></n-form-item><n-form-item label="新密码"><n-input v-model:value="newPassword" type="password" show-password-on="click" placeholder="至少 12 个字符"/></n-form-item><n-form-item label="确认新密码"><n-input v-model:value="confirmPassword" type="password" show-password-on="click"/></n-form-item><n-button type="primary" :loading="changing" @click="changePassword">更新密码</n-button></n-form></div></section>
<n-modal v-model:show="reauthOpen" :mask-closable="false"><div class="surface w-[min(420px,calc(100vw-32px))] p-5"><div class="mb-1 flex items-center gap-2 text-lg font-semibold"><ShieldCheck :size="20" class="cf-orange"/>验证身份</div><p class="mb-5 text-sm text-gray-500">继续前需要再次确认管理员身份</p><n-button block :loading="reauthLoading" @click="reauthPasskey"><template #icon><KeyRound :size="17"/></template>使用 Passkey</n-button><div class="my-4 flex items-center gap-2 text-xs text-gray-400"><span class="h-px flex-1 bg-gray-200 dark:bg-gray-700"></span>或<span class="h-px flex-1 bg-gray-200 dark:bg-gray-700"></span></div><n-input v-model:value="reauthPassword" type="password" show-password-on="click" placeholder="管理员密码" @keyup.enter="reauthPasswordSubmit"/><div class="mt-4 flex justify-end gap-2"><n-button @click="reauthOpen=false;pending=null">取消</n-button><n-button type="primary" :loading="reauthLoading" @click="reauthPasswordSubmit">验证</n-button></div></div></n-modal>
<n-modal v-model:show="nameOpen"><div class="surface w-[min(400px,calc(100vw-32px))] p-5"><h3 class="text-lg font-semibold">{{renameTarget?'重命名 Passkey':'注册 Passkey'}}</h3><n-form-item label="设备名称" class="mt-4"><n-input v-model:value="passkeyName" autofocus placeholder="例如：MacBook Touch ID" @keyup.enter="saveName"/></n-form-item><div class="flex justify-end gap-2"><n-button @click="nameOpen=false">取消</n-button><n-button type="primary" @click="saveName">继续</n-button></div></div></n-modal></div></template>
