<script setup lang="ts">
import { h, onMounted, ref } from 'vue'
import { NButton, NPopconfirm, NTag, type DataTableColumns, useMessage } from 'naive-ui'
import { Plus, RefreshCw, Trash2 } from '@lucide/vue'
import { api } from '@/api'
import { useAppStore } from '@/stores/app'
interface Token {id:number;name:string;status:string;last_error:string;zone_count:number;last_verified_at?:string;created_at:string}
const items=ref<Token[]>([]),loading=ref(false),drawer=ref(false),saving=ref(false),name=ref(''),token=ref(''),message=useMessage(),app=useAppStore()
const drawerWidth=Math.min(480,window.innerWidth)
const load=async()=>{loading.value=true;try{items.value=await api.request('/tokens')}catch(e:any){message.error(e.message)}finally{loading.value=false}}
const add=async()=>{saving.value=true;try{await api.request('/tokens',{method:'POST',body:JSON.stringify({name:name.value,token:token.value})});drawer.value=false;name.value='';token.value='';await Promise.all([load(),app.loadZones()]);message.success('API Token 已添加并完成域名同步')}catch(e:any){message.error(e.message)}finally{saving.value=false}}
const sync=async(row:Token)=>{try{await api.request(`/tokens/${row.id}/sync`,{method:'POST',body:'{}'});await Promise.all([load(),app.loadZones()]);message.success('同步完成')}catch(e:any){message.error(e.message)}}
const remove=async(row:Token)=>{try{await api.request(`/tokens/${row.id}`,{method:'DELETE'});await Promise.all([load(),app.loadZones()]);message.success('API Token 已删除')}catch(e:any){message.error(e.message)}}
const columns:DataTableColumns<Token>=[{title:'名称',key:'name',render:r=>h('div',[h('div',{class:'font-semibold'},r.name),r.last_error?h('div',{class:'mt-1 max-w-[420px] truncate text-xs text-red-500'},r.last_error):null])},{title:'状态',key:'status',width:110,render:r=>h(NTag,{size:'small',type:r.status==='valid'?'success':'error',bordered:false},{default:()=>r.status==='valid'?'有效':'异常'})},{title:'Zone',key:'zone_count',width:90},{title:'最后验证',key:'last_verified_at',width:180,render:r=>r.last_verified_at?new Date(r.last_verified_at).toLocaleString():'-'},{title:'操作',key:'actions',width:110,render:r=>h('div',{class:'flex gap-1'},[h(NButton,{quaternary:true,circle:true,onClick:()=>sync(r)},{icon:()=>h(RefreshCw,{size:16})}),h(NPopconfirm,{onPositiveClick:()=>remove(r)},{trigger:()=>h(NButton,{quaternary:true,circle:true,type:'error'},{icon:()=>h(Trash2,{size:16})}),default:()=>`删除 ${r.name} 及其本地 Zone 缓存？`})])}]
onMounted(load)
</script>
<template><div><div class="mb-5 flex items-start justify-between gap-4"><div><h1 class="page-title">API Token</h1><p class="page-subtitle">Token 使用 AES-256-GCM 加密后保存在本机</p></div><n-button type="primary" @click="drawer=true"><template #icon><Plus :size="17"/></template>添加 Token</n-button></div><n-alert type="info" class="mb-4" :bordered="false">Cloudflare Token 需要 <b>Zone:DNS:Edit</b> 与 <b>Zone:Zone:Read</b> 权限。</n-alert><div class="surface overflow-hidden"><n-data-table v-if="loading||items.length" :columns="columns" :data="items" :loading="loading" :bordered="false" :row-key="(r:Token)=>r.id"/><n-empty v-else class="py-16" description="尚未添加 API Token"/></div><n-drawer v-model:show="drawer" placement="right" :width="drawerWidth"><n-drawer-content title="添加 Cloudflare API Token" closable><n-form><n-form-item label="名称"><n-input v-model:value="name" placeholder="例如：个人账户"/></n-form-item><n-form-item label="API Token"><n-input v-model:value="token" type="password" show-password-on="click" placeholder="Token 仅在提交时发送"/></n-form-item></n-form><template #footer><n-space><n-button @click="drawer=false">取消</n-button><n-button type="primary" :loading="saving" @click="add">验证并添加</n-button></n-space></template></n-drawer-content></n-drawer></div></template>
